### ISSUE TITLE
zwface的论文

### ISSUE THREAD

**Issue by zys1994** [olojuwin/facerecognize-for-mobile-phone#10]
zwface的有相关的论文吗？方便的话给我发个链接，我想了解一下思路

**Comment by olojuwin** [comment]
@zys1994 你好，没有发论文，因为这个结果并没有做好，后期还会更新。如果需要相关论文，可以参考以下链接的论文，http://openaccess.thecvf.com/ICCV2019_workshops/ICCV2019_LSR.py
