### ISSUE TITLE
训练方法后续会有公开吗？

### ISSUE THREAD

**Issue by jeremycheong** [olojuwin/facerecognize-for-mobile-phone#2]
训练方法后续会有公开吗？学习一下，我训练这个模型最好效果将近达到作者公布的数据。

**Comment by olojuwin** [comment]
> 训练方法后续会有公开吗？学习一下，我训练这个模型最好效果将近达到作者公布的数据。

主要是训练数据不一样吧

**Comment by HaynesRuan** [comment]
@olojuwin 博主，请问训练的数据是自己做的数据集吗？

**Comment by olojuwin** [comment]
> @olojuwin 博主，请问训练的数据是自己做的数据集吗？

不是
