### ISSUE TITLE
模型大小

### ISSUE THREAD

**Issue by zhanglaplace** [olojuwin/facerecognize-for-mobile-phone#3]
你好，看了下模型大小，你的好像比mobilefacenet的大很多。

**Comment by olojuwin** [comment]
> 你好，看了下模型大小，你的好像比mobilefacenet的大很多。

计算量是一样的，参数量比较大

**Comment by HaynesRuan** [comment]
@olojuwin 博主，请问你提供的模型，怎么能跑起来，是基于那一份git代码？

**Comment by olojuwin** [comment]
> @olojuwin 博主，请问你提供的模型，怎么能跑起来，是基于那一份git代码？

是的，看参考项目

**Comment by JunhuaYe** [comment]
你好，能够跟你请教个问题么，Relu转TFlite，因为他不在TFLite中，没有折腾通，可以指点一下么，我微信18089291021

**Comment by olojuwin** [comment]
> 你好，能够跟你请教个问题么，Relu转TFlite，因为他不在TFLite中，没有折腾通，可以指点一下么，我微信18089291021

没有试过，但应该没有问题的，用的是PRELU

**Comment by JunhuaYe** [comment]
好吧，还是非常感谢，Tensorflow有的OP，lite中的没有对应的OP，生成转换模型，各种问题

发送自 Windows 10 版邮件应用

发件人: juwin
发送时间: 2019年9月2日 9:47
收件人: olojuwin/facerecognize-for-mobile-phone
抄送: JunhuaYe; Comment
主题: Re: [olojuwin/facerecognize-for-mobile-phone] 模型大小 (#3)

你好，能够跟你请教个问题么，Relu转TFlite，因为他不在TFLite中，没有折腾通，可以指点一下么，我微信18089291021
没有试过，但应该没有问题的，用的是PRELU
