### ISSUE TITLE
实际测试，效果并不好？

### ISSUE THREAD

**Issue by baishiruyue** [olojuwin/facerecognize-for-mobile-phone#6]
作者你好，我测试了你训练的mobilefacenet模型（mxnet），lfw,cfp-fp，agedb-30,上的指标非常高，基本与你的说明相同，但是我测试了自己的数据集（静态配合式人脸数据），发现与我自己训练的模型性比，性能差的较多。说明下，我训练的是 (mobilefacenet 128维，就是insightface中的模型，没有做什么修改，用的数据集也是glint 公开数据集，我训练的LFW, cfp-fp，agedb-30的指标都比较低，大概式99.2%，89.1%和 94.2%左右)，我很疑惑，为什么你在验证集上的指标比我高了很多，为什么在我的数据集上性能却有较大差距呐？希望可以和你探讨下这个问题？不知道你有没有在自己的数据集上测试过。

**Comment by olojuwin** [comment]
> 作者你好，我测试了你训练的mobilefacenet模型（mxnet），lfw,cfp-fp，agedb-30,上的指标非常高，基本与你的说明相同，但是我测试了自己的数据集（静态配合式人脸数据），发现与我自己训练的模型性比，性能差的较多。说明下，我训练的是 (mobilefacenet 128维，就是insightface中的模型，没有做什么修改，用的数据集也是glint 公开数据集，我训练的LFW, cfp-fp，agedb-30的指标都比较低，大概式99.2%，89.1%和 94.2%左右)，我很疑惑，为什么你在验证集上的指标比我高了很多，为什么在我的数据集上性能却有较大差距呐？希望可以和你探讨下这个问题？不知道你有没有在自己的数据集上测试过。
你好，首先我选取模型标准以megaface为主，其次我训练数据是比赛数据，不是glint那个数据，比赛数据，详情见insightface

**Comment by baishiruyue** [comment]
@olojuwin 多谢你的回复，我疑问点是验证集指标为什么没有标示出模型的性能呐？

**Comment by olojuwin** [comment]
@baishiruyue 你说的性能是指什么性能？

**Comment by baishiruyue** [comment]
@olojuwin 就是你训练出的模型的lfw，cfp-fp和agedb三个验证集指标都比我自己训的模型的这三个值高了许多，但是在实际测试集（我自己的一个1：10000的测试集，数据基本都是正对摄像头拍摄的人脸数据）上，误识率和漏报率，你的模型都要稍差些？

**Comment by olojuwin** [comment]
@baishiruyue 主要是对齐方式不一样，还有你测试的注意RGB和BGR的区别

**Comment by baishiruyue** [comment]
@olojuwin 我也尝试了RGB和BGR两种方法，和insightface论文相同的RGB输入方式 比 BGR输出性能要好，但是在我自己的数据集上性能还是差了些，所以我也认为主要和对齐方式有关吧，你训练的时候是采用mtcnn对齐的，我是采用retinaface的检测结果进行对齐的，不过感觉性能差别还是有点儿大啊。。。

**Comment by olojuwin** [comment]
@baishiruyue 我的训练数据也是retinface对齐的，训练数据不一样，怎么比？你应该有加格林深瞳亚洲人脸数据，或者说你有自己的私有数据。
