### ISSUE TITLE
作者您好,我想请问下如何进行Megaface的Verification测评,我在devkit里测出来只有rank1

### ISSUE THREAD

**Issue by DLfollower** [olojuwin/facerecognize-for-mobile-phone#9]
如题目所示,还请不吝赐教!感激不尽

**Comment by olojuwin** [comment]
@DLfollower https://github.com/happynear/FaceVerification

**Comment by zys1994** [comment]
测试megaface的run_experiment.py文件是在哪里 我找了好久都没找到，可以告诉我一下吗
